"""initial_schema

Revision ID: 0fc932bde3bc
Revises: 
Create Date: 2026-06-06 12:32:27.229815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fc932bde3bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

userrole = postgresql.ENUM(
    'admin', 'sales_manager', 'sales_agent', 'viewer', name='userrole', create_type=False
)
leadstage = postgresql.ENUM(
    'new', 'contacted', 'qualified', 'proposal', 'negotiation', 'won', 'lost',
    name='leadstage', create_type=False,
)
leadpriority = postgresql.ENUM('low', 'medium', 'high', name='leadpriority', create_type=False)
leadsource = postgresql.ENUM(
    'website', 'referral', 'cold_call', 'social_media', 'email_campaign', 'trade_show', 'other',
    name='leadsource', create_type=False,
)
activitytype = postgresql.ENUM(
    'call', 'email', 'meeting', 'note', 'task', name='activitytype', create_type=False
)


def upgrade() -> None:
    bind = op.get_bind()
    userrole.create(bind, checkfirst=True)
    leadstage.create(bind, checkfirst=True)
    leadpriority.create(bind, checkfirst=True)
    leadsource.create(bind, checkfirst=True)
    activitytype.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', userrole, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('stage', leadstage, nullable=False),
    sa.Column('priority', leadpriority, nullable=False),
    sa.Column('source', leadsource, nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('assigned_to_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_assigned_to_id'), 'leads', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_stage'), 'leads', ['stage'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', activitytype, nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_lead_id'), 'activities', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_lead_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_leads_stage'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_to_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    bind = op.get_bind()
    activitytype.drop(bind, checkfirst=True)
    leadsource.drop(bind, checkfirst=True)
    leadpriority.drop(bind, checkfirst=True)
    leadstage.drop(bind, checkfirst=True)
    userrole.drop(bind, checkfirst=True)
