"""update_attendance_sessions_and_shifts

Revision ID: 5cd03e33e1c9
Revises: a1b2c3d4e5f6
Create Date: 2026-07-10 23:09:10.203654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd03e33e1c9'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_attendance_user_work_date', 'attendance_sessions', type_='unique')
    op.add_column('shift_templates', sa.Column('lunch_break_minutes', sa.Integer(), server_default='30', nullable=False))
    op.add_column('shift_templates', sa.Column('short_break_minutes', sa.Integer(), server_default='15', nullable=False))
    op.add_column('shift_templates', sa.Column('short_break_limit', sa.Integer(), server_default='2', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_templates', 'short_break_limit')
    op.drop_column('shift_templates', 'short_break_minutes')
    op.drop_column('shift_templates', 'lunch_break_minutes')
    op.create_unique_constraint('uq_attendance_user_work_date', 'attendance_sessions', ['user_id', 'work_date'])
    # ### end Alembic commands ###
